import { createTranslationMessages } from "@backstage/core-plugin-api/alpha";
import { catalogImportTranslationRef } from "@backstage/plugin-catalog-import/alpha";

const pt = createTranslationMessages({
    ref: catalogImportTranslationRef,
    full: false,
    messages: {
        "buttons.back": "Voltar",
        "defaultImportPage.headerTitle": "Registrar um componente existente",
        "defaultImportPage.contentHeaderTitle": "Comece a rastrear seu componente no {{appTitle}}",
        "defaultImportPage.supportTitle": "Comece a rastrear seu componente no {{appTitle}} adicionando-o ao catálogo de software.",
        "importInfoCard.title": "Registrar um componente existente",
        "importInfoCard.deepLinkTitle": "Saiba mais sobre o Catálogo de Software",
        "importInfoCard.linkDescription": "Insira o URL do seu repositório de código-fonte para adicioná-lo ao {{appTitle}}.",
        "importInfoCard.fileLinkTitle": "Link para um arquivo de entidade existente",
        "importInfoCard.examplePrefix": "Exemplo: ",
        "importInfoCard.fileLinkDescription": "O assistente analisa o arquivo, pré-visualiza as entidades e as adiciona ao catálogo {{appTitle}}.",
        "importInfoCard.githubIntegration.label": "Apenas GitHub",
        "importInfoCard.githubIntegration.title": "Link para um repositório",
        "importStepper.finish.title": "Concluir",
        "importStepper.noLocation.title": "Criar Pull Request",
        "importStepper.noLocation.createPr.ownerLabel": "Proprietário da Entidade",
        "importStepper.noLocation.createPr.detailsTitle": "Detalhes do Pull Request",
        "importStepper.noLocation.createPr.titleLabel": "Título do Pull Request",
        "importStepper.noLocation.createPr.titlePlaceholder": "Adicionar arquivos descritores de entidade do catálogo Backstage",
        "importStepper.noLocation.createPr.bodyLabel": "Corpo do Pull Request",
        "importStepper.noLocation.createPr.bodyPlaceholder": "Um texto descritivo com suporte a Markdown",
        "importStepper.noLocation.createPr.configurationTitle": "Configuração da Entidade",
        "importStepper.noLocation.createPr.componentNameLabel": "Nome do componente criado",
        "importStepper.noLocation.createPr.componentNamePlaceholder": "meu-componente",
        "importStepper.noLocation.createPr.ownerLoadingText": "Carregando grupos…",
        "importStepper.noLocation.createPr.ownerHelperText": "Selecione um proprietário da lista ou insira uma referência a um Grupo ou um Usuário",
        "importStepper.noLocation.createPr.ownerErrorHelperText": "valor obrigatório",
        "importStepper.noLocation.createPr.ownerPlaceholder": "meu-grupo",
        "importStepper.noLocation.createPr.codeownersHelperText": "AVISO: Isso pode falhar se nenhum arquivo CODEOWNERS for encontrado no local de destino.",
        "importStepper.singleLocation.title": "Selecionar Locais",
        "importStepper.singleLocation.description": "Locais Descobertos: 1",
        "importStepper.multipleLocations.title": "Selecionar Locais",
        "importStepper.multipleLocations.description": "Locais Descobertos: {{length, number}}",
        "importStepper.analyze.title": "Selecionar URL",
        "importStepper.prepare.title": "Ações de Importação",
        "importStepper.prepare.description": "Opcional",
        "importStepper.review.title": "Revisar",
        "stepFinishImportLocation.repository.title": "O seguinte Pull Request foi aberto: ",
        "stepFinishImportLocation.repository.description": "Suas entidades serão importadas assim que o Pull Request for mesclado.",
        "stepFinishImportLocation.backButtonText": "Registrar outro",
        "stepFinishImportLocation.locations.new": "As seguintes entidades foram adicionadas ao catálogo:",
        "stepFinishImportLocation.locations.backButtonText": "Registrar outro",
        "stepFinishImportLocation.locations.existing": "Uma atualização foi acionada para os seguintes locais:",
        "stepFinishImportLocation.locations.viewButtonText": "Visualizar Componente",
        "stepInitAnalyzeUrl.error.default": "Recebemos um resultado de análise desconhecido do tipo {{type}}. Por favor, entre em contato com a equipe de suporte.",
        "stepInitAnalyzeUrl.error.url": "Deve começar com http:// ou https://.",
        "stepInitAnalyzeUrl.error.repository": "Não foi possível gerar entidades para seu repositório",
        "stepInitAnalyzeUrl.error.locations": "Não há entidades neste local",
        "stepInitAnalyzeUrl.urlHelperText": "Insira o caminho completo para o arquivo de sua entidade para começar a rastrear seu componente",
        "stepInitAnalyzeUrl.nextButtonText": "Analisar",
        "stepPrepareCreatePullRequest.nextButtonText": "Criar PR",
        "stepPrepareCreatePullRequest.previewPr.title": "Pré-visualizar Pull Request",
        "stepPrepareCreatePullRequest.previewPr.subheader": "Criar um novo Pull Request",
        "stepPrepareCreatePullRequest.previewCatalogInfo.title": "Pré-visualizar Entidades",
        "stepPrepareSelectLocations.locations.description": "Selecione um ou mais locais que estão presentes em seu repositório git:",
        "stepPrepareSelectLocations.locations.selectAll": "Selecionar Tudo",
        "stepPrepareSelectLocations.nextButtonText": "Revisar",
        "stepPrepareSelectLocations.existingLocations.description": "Esses locais já existem no catálogo:",
        "stepReviewLocation.refresh": "Atualizar",
        "stepReviewLocation.import": "Importar",
        "stepReviewLocation.catalog.new": "As seguintes entidades serão adicionadas ao catálogo:",
        "stepReviewLocation.catalog.exists": "Os seguintes locais já existem no catálogo:",
        "stepReviewLocation.prepareResult.title": "O seguinte Pull Request foi aberto: ",
        "stepReviewLocation.prepareResult.description": "Você já pode importar o local e {{appTitle}} buscará as entidades assim que o Pull Request for mesclado."
    }
});

export default pt;

