import { createTranslationMessages } from "@backstage/core-plugin-api/alpha";
import { catalogTranslationRef } from "@backstage/plugin-catalog/alpha";

const pt = createTranslationMessages({
    ref: catalogTranslationRef,
    full: false,
    messages: {
        "deleteEntity.description": "Esta entidade não é referenciada por nenhum local e, portanto, não está recebendo atualizações. Clique aqui para excluir.",
        "deleteEntity.cancelButtonTitle": "Cancelar",
        "deleteEntity.deleteButtonTitle": "Excluir",
        "deleteEntity.dialogTitle": "Tem certeza de que deseja excluir esta entidade?",
        "indexPage.title": "Catálogo {{orgName}}",
        "indexPage.createButtonTitle": "Criar",
        "indexPage.supportButtonContent": "Todas as entidades do seu catálogo de software",
        "aboutCard.title": "Sobre",
        "aboutCard.refreshButtonTitle": "Agendar atualização da entidade",
        "aboutCard.editButtonTitle": "Editar Metadados",
        "aboutCard.createSimilarButtonTitle": "Criar algo semelhante",
        "aboutCard.refreshScheduledMessage": "Atualização agendada",
        "aboutCard.launchTemplate": "Iniciar Modelo",
        "aboutCard.viewTechdocs": "Ver TechDocs",
        "aboutCard.viewSource": "Ver Código Fonte",
        "aboutCard.descriptionField.value": "Nenhuma descrição",
        "aboutCard.descriptionField.label": "Descrição",
        "aboutCard.ownerField.value": "Nenhum Proprietário",
        "aboutCard.ownerField.label": "Proprietário",
        "aboutCard.domainField.value": "Nenhum Domínio",
        "aboutCard.domainField.label": "Domínio",
        "aboutCard.systemField.value": "Nenhum Sistema",
        "aboutCard.systemField.label": "Sistema",
        "aboutCard.parentComponentField.value": "Nenhum Componente Pai",
        "aboutCard.parentComponentField.label": "Componente Pai",
        "aboutCard.typeField.label": "Tipo",
        "aboutCard.lifecycleField.label": "Ciclo de Vida",
        "aboutCard.tagsField.value": "Nenhuma Tag",
        "aboutCard.tagsField.label": "Tags",
        "aboutCard.targetsField.label": "Alvos",
        "searchResultItem.lifecycle": "Ciclo de Vida",
        "searchResultItem.Owner": "Proprietário",
        "catalogTable.warningPanelTitle": "Não foi possível buscar entidades do catálogo.",
        "catalogTable.viewActionTitle": "Visualizar",
        "catalogTable.editActionTitle": "Editar",
        "catalogTable.starActionTitle": "Adicionar aos favoritos",
        "catalogTable.unStarActionTitle": "Remover dos favoritos",
        "dependencyOfComponentsCard.title": "Dependência de componentes",
        "dependencyOfComponentsCard.emptyMessage": "Nenhum componente depende deste componente",
        "dependsOnComponentsCard.title": "Depende de componentes",
        "dependsOnComponentsCard.emptyMessage": "Nenhum componente é uma dependência deste componente",
        "dependsOnResourcesCard.title": "Depende de recursos",
        "dependsOnResourcesCard.emptyMessage": "Nenhum recurso é uma dependência deste componente",
        "entityContextMenu.copiedMessage": "Copiado!",
        "entityContextMenu.moreButtonTitle": "Mais",
        "entityContextMenu.inspectMenuTitle": "Inspecionar entidade",
        "entityContextMenu.copyURLMenuTitle": "Copiar URL da entidade",
        "entityContextMenu.unregisterMenuTitle": "Remover registro da entidade",
        "entityLabelsCard.title": "Rótulos",
        "entityLabelsCard.emptyDescription": "Nenhum rótulo definido para esta entidade. Você pode adicionar rótulos ao seu YAML de entidade conforme mostrado no exemplo destacado abaixo:",
        "entityLabelsCard.readMoreButtonTitle": "Ler mais",
        "entityLabels.warningPanelTitle": "Entidade não encontrada",
        "entityLabels.ownerLabel": "Proprietário",
        "entityLabels.lifecycleLabel": "Ciclo de Vida",
        "entityLinksCard.title": "Links",
        "entityLinksCard.emptyDescription": "Nenhum link definido para esta entidade. Você pode adicionar links ao seu YAML de entidade conforme mostrado no exemplo destacado abaixo:",
        "entityLinksCard.readMoreButtonTitle": "Ler mais",
        "entityNotFound.title": "Entidade não encontrada",
        "entityNotFound.description": "Quer nos ajudar a construir isso? Confira nossa documentação de Introdução.",
        "entityNotFound.docButtonTitle": "DOCUMENTOS",
        "entityProcessingErrorsDescription": "O erro abaixo se origina de",
        "entityRelationWarningDescription": "Esta entidade possui relações com outras entidades, que não podem ser encontradas no catálogo.\n As entidades não encontradas são: ",
        "hasComponentsCard.title": "Tem componentes",
        "hasComponentsCard.emptyMessage": "Nenhum componente faz parte deste sistema",
        "hasResourcesCard.title": "Tem recursos",
        "hasResourcesCard.emptyMessage": "Nenhum recurso faz parte deste sistema",
        "hasSubcomponentsCard.title": "Tem subcomponentes",
        "hasSubcomponentsCard.emptyMessage": "Nenhum subcomponente faz parte deste componente",
        "hasSubdomainsCard.title": "Tem subdomínios",
        "hasSubdomainsCard.emptyMessage": "Nenhum subdomínio faz parte deste domínio",
        "hasSystemsCard.title": "Tem sistemas",
        "hasSystemsCard.emptyMessage": "Nenhum sistema faz parte deste domínio",
        "relatedEntitiesCard.emptyHelpLinkTitle": "Saiba como alterar isso",
        "systemDiagramCard.title": "Diagrama do Sistema",
        "systemDiagramCard.description": "Use o movimento de pinça e zoom para mover-se pelo diagrama.",
        "systemDiagramCard.edgeLabels.dependsOn": "depende de",
        "systemDiagramCard.edgeLabels.partOf": "parte de",
        "systemDiagramCard.edgeLabels.provides": "fornece"
    },
});

export default pt;