import { createTranslationMessages } from "@backstage/core-plugin-api/alpha";
import { scaffolderTranslationRef } from "@backstage/plugin-scaffolder/alpha";

const pt = createTranslationMessages({
    ref: scaffolderTranslationRef,
    full: false,
    messages: {
        "fields.entityNamePicker.title": "Nome",
        "fields.entityNamePicker.description": "Nome único do componente",
        "fields.entityPicker.title": "Entidade",
        "fields.entityPicker.description": "Uma entidade do catálogo",
        "fields.entityTagsPicker.title": "Tags",
        "fields.entityTagsPicker.description": "Adicione tags relevantes, pressione 'Enter' para adicionar novas tags. Formato válido: [a-z0-9+#] separados por [-], no máximo 63 caracteres",
        "fields.multiEntityPicker.title": "Entidade",
        "fields.multiEntityPicker.description": "Uma entidade do catálogo",
        "fields.myGroupsPicker.title": "Entidade",
        "fields.myGroupsPicker.description": "Uma entidade do catálogo",
        "fields.ownedEntityPicker.title": "Entidade",
        "fields.ownedEntityPicker.description": "Uma entidade do catálogo",
        "fields.ownerPicker.title": "Proprietário",
        "fields.ownerPicker.description": "O proprietário do componente",
        "fields.azureRepoPicker.organization.title": "Organização",
        "fields.azureRepoPicker.organization.description": "A Organização à qual este repositório pertencerá",
        "fields.azureRepoPicker.project.title": "Projeto",
        "fields.azureRepoPicker.project.description": "O Projeto ao qual este repositório pertencerá",
        "fields.bitbucketRepoPicker.project.title": "Projetos Permitidos",
        "fields.bitbucketRepoPicker.project.description": "O Projeto ao qual este repositório pertencerá",
        "fields.bitbucketRepoPicker.project.inputTitle": "Projetos",
        "fields.bitbucketRepoPicker.workspaces.title": "Workspaces Permitidos",
        "fields.bitbucketRepoPicker.workspaces.description": "O Workspace ao qual este repositório pertencerá",
        "fields.bitbucketRepoPicker.workspaces.inputTitle": "Workspaces",
        "fields.gerritRepoPicker.parent.title": "Pai",
        "fields.gerritRepoPicker.parent.description": "O projeto pai ao qual o repositório pertencerá",
        "fields.gerritRepoPicker.owner.title": "Proprietário",
        "fields.gerritRepoPicker.owner.description": "O proprietário do projeto (opcional)",
        "fields.giteaRepoPicker.owner.title": "Proprietário Disponível",
        "fields.giteaRepoPicker.owner.description": "Namespace Gitea ao qual este repositório pertencerá. Pode ser o nome da organização, grupo, subgrupo, usuário ou projeto.",
        "fields.giteaRepoPicker.owner.inputTitle": "Proprietário",
        "fields.githubRepoPicker.owner.title": "Proprietário Disponível",
        "fields.githubRepoPicker.owner.description": "A organização, usuário ou projeto ao qual este repositório pertencerá",
        "fields.githubRepoPicker.owner.inputTitle": "Proprietário",
        "fields.gitlabRepoPicker.owner.title": "Proprietário Disponível",
        "fields.gitlabRepoPicker.owner.description": "Namespace GitLab ao qual este repositório pertencerá. Pode ser o nome da organização, grupo, subgrupo, usuário ou projeto.",
        "fields.gitlabRepoPicker.owner.inputTitle": "Proprietário",
        "fields.repoUrlPicker.host.title": "Host",
        "fields.repoUrlPicker.host.description": "O host onde o repositório será criado",
        "fields.repoUrlPicker.repository.title": "Repositórios Disponíveis",
        "fields.repoUrlPicker.repository.description": "O nome do repositório",
        "fields.repoUrlPicker.repository.inputTitle": "Repositório",
        "actionsPage.content.emptyState.title": "Nenhuma informação para exibir",
        "actionsPage.content.emptyState.description": "Não há ações instaladas ou houve um problema de comunicação com o backend.",
        "actionsPage.content.searchFieldPlaceholder": "Buscar uma ação",
        "actionsPage.title": "Ações instaladas",
        "actionsPage.action.input": "Entrada",
        "actionsPage.action.output": "Saída",
        "actionsPage.action.examples": "Exemplos",
        "actionsPage.subtitle": "Esta é a coleção de todas as ações instaladas",
        "actionsPage.pageTitle": "Criar um Novo Componente",
        "listTaskPage.content.emptyState.title": "Nenhuma informação para exibir",
        "listTaskPage.content.emptyState.description": "Não há tarefas ou houve um problema de comunicação com o backend.",
        "listTaskPage.content.tableCell.template": "Modelo",
        "listTaskPage.content.tableCell.status": "Status",
        "listTaskPage.content.tableCell.owner": "Proprietário",
        "listTaskPage.content.tableCell.created": "Criado",
        "listTaskPage.content.tableCell.taskID": "ID da Tarefa",
        "listTaskPage.content.tableTitle": "Tarefas",
        "listTaskPage.title": "Listar tarefas de modelo",
        "listTaskPage.subtitle": "Todas as tarefas que foram iniciadas",
        "listTaskPage.pageTitle": "Tarefas de Modelos",
        "ownerListPicker.title": "Proprietário da Tarefa",
        "ownerListPicker.options.all": "Todos",
        "ownerListPicker.options.owned": "Próprios",
        "ongoingTask.title": "Execução de",
        "ongoingTask.contextMenu.cancel": "Cancelar",
        "ongoingTask.contextMenu.startOver": "Começar Novamente",
        "ongoingTask.contextMenu.retry": "Tentar Novamente",
        "ongoingTask.contextMenu.hideLogs": "Ocultar Logs",
        "ongoingTask.contextMenu.showLogs": "Mostrar Logs",
        "ongoingTask.contextMenu.hideButtonBar": "Ocultar Barra de Botões",
        "ongoingTask.contextMenu.showButtonBar": "Mostrar Barra de Botões",
        "ongoingTask.subtitle": "Tarefa {{taskId}}",
        "ongoingTask.pageTitle.hasTemplateName": "Execução de {{templateName}}",
        "ongoingTask.pageTitle.noTemplateName": "Execução do Scaffolder",
        "ongoingTask.cancelButtonTitle": "Cancelar",
        "ongoingTask.retryButtonTitle": "Tentar Novamente",
        "ongoingTask.startOverButtonTitle": "Começar Novamente",
        "ongoingTask.hideLogsButtonTitle": "Ocultar Logs",
        "ongoingTask.showLogsButtonTitle": "Mostrar Logs",
        "templateEditorForm.stepper.emptyText": "Não há parâmetros de especificação no modelo para pré-visualizar.",
        "renderSchema.undefined": "Nenhum esquema definido",
        "renderSchema.tableCell.name": "Nome",
        "renderSchema.tableCell.type": "Tipo",
        "renderSchema.tableCell.title": "Título",
        "renderSchema.tableCell.description": "Descrição",
        "templatingExtensions.content.values.title": "Valores",
        "templatingExtensions.content.values.notAvailable": "Não há valores de modelo globais definidos.",
        "templatingExtensions.content.emptyState.title": "Nenhuma informação para exibir",
        "templatingExtensions.content.emptyState.description": "Não há extensões de modelagem disponíveis ou houve um problema de comunicação com o backend.",
        "templatingExtensions.content.filters.title": "Filtros",
        "templatingExtensions.content.filters.schema.input": "Entrada",
        "templatingExtensions.content.filters.schema.output": "Saída",
        "templatingExtensions.content.filters.schema.arguments": "Argumentos",
        "templatingExtensions.content.filters.examples": "Exemplos",
        "templatingExtensions.content.filters.notAvailable": "Não há filtros de modelo definidos.",
        "templatingExtensions.content.filters.metadataAbsent": "Metadados do filtro indisponíveis",
        "templatingExtensions.content.searchFieldPlaceholder": "Buscar uma extensão",
        "templatingExtensions.content.functions.title": "Funções",
        "templatingExtensions.content.functions.schema.output": "Saída",
        "templatingExtensions.content.functions.schema.arguments": "Argumentos",
        "templatingExtensions.content.functions.examples": "Exemplos",
        "templatingExtensions.content.functions.notAvailable": "Não há funções de modelo globais definidas.",
        "templatingExtensions.title": "Extensões de Modelagem",
        "templatingExtensions.subtitle": "Esta é a coleção de extensões de modelagem disponíveis",
        "templatingExtensions.pageTitle": "Extensões de Modelagem",
        "templateTypePicker.title": "Categorias",
        "templateIntroPage.title": "Gerenciar Modelos",
        "templateIntroPage.subtitle": "Edite, pré-visualize e experimente modelos, formulários e campos personalizados",
        "templateFormPage.title": "Editor de Modelo",
        "templateFormPage.subtitle": "Edite, pré-visualize e experimente formulários de modelos",
        "templateCustomFieldPage.title": "Explorador de Campo Personalizado",
        "templateCustomFieldPage.subtitle": "Edite, pré-visualize e experimente campos personalizados",
        "templateEditorPage.title": "Editor de Modelo",
        "templateEditorPage.subtitle": "Edite, pré-visualize e experimente modelos e formulários de modelo",
        "templateEditorPage.dryRunResults.title": "Resultados da execução simulada",
        "templateEditorPage.dryRunResultsList.title": "Resultado {{resultId}}",
        "templateEditorPage.dryRunResultsList.deleteButtonTitle": "Excluir resultado",
        "templateEditorPage.dryRunResultsList.downloadButtonTitle": "Baixar como .zip",
        "templateEditorPage.dryRunResultsView.tab.output": "Saída",
        "templateEditorPage.dryRunResultsView.tab.log": "Log",
        "templateEditorPage.dryRunResultsView.tab.files": "Arquivos",
        "templateEditorPage.taskStatusStepper.skippedStepTitle": "Ignorado",
        "templateEditorPage.customFieldExplorer.preview.title": "Especificação do Modelo",
        "templateEditorPage.customFieldExplorer.fieldForm.title": "Opções de Campo",
        "templateEditorPage.customFieldExplorer.fieldForm.applyButtonTitle": "Aplicar",
        "templateEditorPage.customFieldExplorer.selectFieldLabel": "Escolher Extensão de Campo Personalizado",
        "templateEditorPage.customFieldExplorer.fieldPreview.title": "Pré-visualização do Campo",
        "templateEditorPage.templateEditorBrowser.closeConfirmMessage": "Tem certeza? As alterações não salvas serão perdidas",
        "templateEditorPage.templateEditorBrowser.saveIconTooltip": "Salvar todos os arquivos",
        "templateEditorPage.templateEditorBrowser.reloadIconTooltip": "Recarregar diretório",
        "templateEditorPage.templateEditorBrowser.closeIconTooltip": "Fechar diretório",
        "templateEditorPage.templateEditorIntro.title": "Comece escolhendo uma das opções abaixo",
        "templateEditorPage.templateEditorIntro.loadLocal.title": "Carregar Diretório de Modelo",
        "templateEditorPage.templateEditorIntro.loadLocal.description": "Carrega um diretório de modelo local, permitindo que você edite e tente executar seu próprio modelo.",
        "templateEditorPage.templateEditorIntro.loadLocal.unsupportedTooltip": "Compatível apenas em alguns navegadores baseados em Chromium com a página carregada via HTTPS",
        "templateEditorPage.templateEditorIntro.createLocal.title": "Criar Novo Modelo",
        "templateEditorPage.templateEditorIntro.createLocal.description": "Cria um diretório de modelo local, permitindo que você edite e tente executar seu próprio modelo.",
        "templateEditorPage.templateEditorIntro.createLocal.unsupportedTooltip": "Compatível apenas em alguns navegadores baseados em Chromium com a página carregada via HTTPS",
        "templateEditorPage.templateEditorIntro.formEditor.title": "Área de Testes de Formulários de Modelo",
        "templateEditorPage.templateEditorIntro.formEditor.description": "Pré-visualize e edite um formulário de modelo, usando um modelo de exemplo ou carregando um modelo do catálogo.",
        "templateEditorPage.templateEditorIntro.fieldExplorer.title": "Explorador de Campo Personalizado",
        "templateEditorPage.templateEditorIntro.fieldExplorer.description": "Visualize e experimente as extensões de campo personalizadas instaladas disponíveis.",
        "templateEditorPage.templateEditorTextArea.saveIconTooltip": "Salvar arquivo",
        "templateEditorPage.templateEditorTextArea.refreshIconTooltip": "Recarregar arquivo",
        "templateEditorPage.templateEditorTextArea.emptyStateParagraph": "Por favor, selecione uma ação no menu de arquivos.",
        "templateEditorPage.templateFormPreviewer.title": "Carregar Modelo Existente",
        "templateListPage.title": "Criar um novo componente",
        "templateListPage.subtitle": "Crie novos componentes de software usando modelos padrão em sua organização",
        "templateListPage.pageTitle": "Criar um novo componente",
        "templateListPage.templateGroups.defaultTitle": "Modelos",
        "templateListPage.templateGroups.otherTitle": "Outros Modelos",
        "templateListPage.contentHeader.supportButtonTitle": "Crie novos componentes de software usando modelos padrão. Diferentes modelos criam diferentes tipos de componentes (serviços, sites, documentação, ...).",
        "templateListPage.contentHeader.registerExistingButtonTitle": "Registrar Componente Existente",
        "templateListPage.additionalLinksForEntity.viewTechDocsTitle": "Visualizar TechDocs",
        "templateWizardPage.title": "Criar um novo componente",
        "templateWizardPage.subtitle": "Crie novos componentes de software usando modelos padrão em sua organização",
        "templateWizardPage.pageTitle": "Criar um novo componente",
        "templateWizardPage.pageContextMenu.editConfigurationTitle": "Editar Configuração",
        "templateEditorToolbar.customFieldExplorerTooltip": "Explorador de Campos Personalizados",
        "templateEditorToolbar.installedActionsDocumentationTooltip": "Documentação de Ações Instaladas",
        "templateEditorToolbar.templatingExtensionsDocumentationTooltip": "Documentação de Extensões de Modelagem",
        "templateEditorToolbar.addToCatalogButton": "Publicar",
        "templateEditorToolbar.addToCatalogDialogTitle": "Publicar alterações",
        "templateEditorToolbar.addToCatalogDialogContent.stepsIntroduction": "Siga as instruções abaixo para criar ou atualizar um modelo:",
        "templateEditorToolbar.addToCatalogDialogContent.stepsListItems": "Salve os arquivos do modelo em um diretório local\nCrie um pull request para um repositório git novo ou existente\nSe o modelo já existir, as alterações serão refletidas no catálogo de software assim que o pull request for mesclado\nMas se você estiver criando um novo modelo, siga a documentação linkada abaixo para registrar o novo repositório de modelo no catálogo de software",
        "templateEditorToolbar.addToCatalogDialogActions.documentationUrl": "https://backstage.io/docs/features/software-templates/adding-templates/",
        "templateEditorToolbar.addToCatalogDialogActions.documentationButton": "Ir para a documentação",
        "templateEditorToolbarFileMenu.button": "Arquivo",
        "templateEditorToolbarFileMenu.options.openDirectory": "Abrir diretório do modelo",
        "templateEditorToolbarFileMenu.options.createDirectory": "Criar diretório do modelo",
        "templateEditorToolbarFileMenu.options.closeEditor": "Fechar editor de modelo",
        "templateEditorToolbarTemplatesMenu.button": "Modelos"
    },
});

export default pt;